### ISSUE TITLE
Release of 0.4.21 three hours ago caused the install script to stop working

### ISSUE THREAD

**Issue by grays42** [wildfoundry/dataplicity-agent#26]
Configuring a bunch of Pis, in the middle the script stopped installing (URL 404'd out). I copied the install script to https://pastebin.com/raw/[redacted] and changed to 0.4.21a3 and it installed fine.

Note--will this workaround cause issues or is 0.4.21a3 effectively the same? (I think so, but I almost never use github.)

Pastebin had my token on it, I changed the line:

"agent_download_url": "https://github.com/wildfoundry/dataplicity-agent/releases/download/v0.4.21a3/dataplicity",

**Comment by barfle** [comment]
There are no material changes from a3.  Confirmed the issue though. Working on it.

**Comment by barfle** [comment]
We've reuploaded the build and it appears to work now.

**Comment by grays42** [comment]
Thanks!

**Comment by barfle** [comment]
Sorry for the inconvenience.
