### ISSUE TITLE
Dataplicity on Rasprian Stratch not working

### ISSUE THREAD

**Issue by yarharel** [wildfoundry/dataplicity-agent#38]
Dataplicity keep being killed every 25 second by supervisor service:
supervisor version 3.3.1
Dataplicity 0.4.29 i think (latest one)

dataplicity@b827eb3c22a1:/$ tail /var/log/syslog -n1000 | grep supervi
Jan 14 20:22:35 b827eb3c22a1 supervisord[405]: 2018-01-14 20:22:35,964 INFO waiting for tuxtunnel to die
Jan 14 20:22:35 b827eb3c22a1 supervisorctl[1612]: Shut down
Jan 14 20:22:35 b827eb3c22a1 supervisord[405]: 2018-01-14 20:22:35,969 INFO stopped: tuxtunnel (terminated by SIGTERM)
Jan 14 20:22:45 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:45,519 CRIT Supervisor running as root (no user in config file)
Jan 14 20:22:45 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:45,519 WARN For [program:tuxtunnel], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
Jan 14 20:22:45 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:45,519 INFO Included extra file "/etc/supervisor/conf.d/tuxtunnel.conf" during parsing
Jan 14 20:22:45 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:45,631 INFO RPC interface 'supervisor' initialized
Jan 14 20:22:45 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:45,633 INFO supervisord started with pid 1671
Jan 14 20:22:46 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:46,640 INFO spawned: 'tuxtunnel' with pid 1679
Jan 14 20:22:47 b827eb3c22a1 supervisord[1671]: 2018-01-14 20:22:47,644 INFO success: tuxtunnel entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by p1r473** [comment]
Same, how did you fix it @Radoslaw-K ?
