### ISSUE TITLE
Cannot see the device on the web interface

### ISSUE THREAD

**Issue by paulstav** [wildfoundry/dataplicity-agent#50]
I have the agent service running and it's reporting no issues.
However, when I log onto the website I cannot see the device anywhere.

Is it locked to work only for RPi devices ?

**Comment by paulstav** [comment]
Will do, thank you for the prompt response.

**Comment by barfle** [comment]
Welcome.  I'm going to close out this ticket here in the hope that we see you shortly on our support line :)

Best,
Elliot.
