### ISSUE TITLE
Unable to connect to remote device after use of Stacer

### ISSUE THREAD

**Issue by mymggithub** [wildfoundry/dataplicity-agent#62]
Hello I am currently having problems with my dataplicity device its showing "Unable to connect to remote device" after running Stacer.

![image](https://user-images.githubusercontent.com/21014768/82159004-044ab800-9851-11ea-8c8a-9ed68dd67650.png)

Problems even still continue after a reinstall attempt
![image](https://user-images.githubusercontent.com/21014768/82159092-7c18e280-9851-11ea-8307-bb99f06d7e9e.png)

After some testing of reinstalling the os I think the problem develops after using the Stacer app.

![image](https://user-images.githubusercontent.com/21014768/82159159-ee89c280-9851-11ea-8070-00fb90cc7f2c.png)

any way this can be fixed to make dataplicity a little more sturdy?

I notice that the dataplicity user is not loading from watching htop.

Thank you for your time.

**Comment by mymggithub** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/21014768/82273116-2f610480-9942-11ea-90f2-d9c995f5faa6.png)
I noticed that the problem has to do with the log files being erased.
But I cant find which one being erased it having the problem.
it doesn't seam to be a problem that can be fixed by just saving the dataplicity.log

**Comment by Radoslaw-K** [comment]
Hey there!

Yes! Supervisor logs need to be kept. As well as that please make sure that the supervisor log **directory** exists during boot-up of your system. If it doesn't - problems will occur. 

Does that help ? 🤗

**Comment by mymggithub** [comment]
Thanks, it does
