### ISSUE TITLE
Password for Dataplicity

### ISSUE THREAD

**Issue by adasio98** [wildfoundry/dataplicity-agent#63]
When i trying to run sudo mode it ask me for dataplicity password.
I tried raspberry pi pass and dataplicity account pass but dont work.
https://prnt.sc/t4lfwb

**Comment by barfle** [comment]
Does this help? https://docs.dataplicity.com/docs/superuser

Pay careful attention re when to use sudo and when to use su. Get them the wrong way around and it won’t work :-)

Best
Elliot

**Comment by adasio98** [comment]
OHHHH OK
Wrong command
