### ISSUE TITLE
Doesn't work with Python 2 and 3

### ISSUE THREAD

**Issue by Temder** [wildfoundry/dataplicity-agent#83]
I freshly installed an ubuntu server on my raspberry pi and wanted to install dataplicity. I have both Python 2 and 3 installed. Installing dataplicity with the command works with a `2` or `3` added behind `python` but the `dataplicity.log` file gives me this output:

`/usr/bin/env: 'python': No such file or directory`

Is there a script that I can edit like the installation command so dataplicity works?

**Comment by toudi** [comment]
hello. we are working on a fix for this problem. Sorry for the inconvenience

**Comment by Temder** [comment]
> @Temder could you try reinstalling the agent ? It should fix the problem. You would still need to use explicit python version in the install command though (so python2/python3 instead of just python)

Thanks but I found another way of dealing with this problem: I installed a program that gives python commands to the python3 command
